// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX3Er7LE-vTnpQVsHrwphuS6Fn2xyx2I0',
    appId: '1:479462375089:web:5ad49091bb839ae9206c90',
    messagingSenderId: '479462375089',
    projectId: 'quartermaster-firebase',
    authDomain: 'quartermaster-firebase.firebaseapp.com',
    databaseURL: 'https://quartermaster-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'quartermaster-firebase.appspot.com',
    measurementId: 'G-8CTPQFJEFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZLuyaMbPSv1o35Af1TkwXVpEcFOIgQY0',
    appId: '1:479462375089:android:e9d67dc13fd1b286206c90',
    messagingSenderId: '479462375089',
    projectId: 'quartermaster-firebase',
    databaseURL: 'https://quartermaster-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'quartermaster-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDifa0oceyhMXBv4y1xnv2sPMVUT9dbi3o',
    appId: '1:479462375089:ios:308dcc204c110c1a206c90',
    messagingSenderId: '479462375089',
    projectId: 'quartermaster-firebase',
    databaseURL: 'https://quartermaster-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'quartermaster-firebase.appspot.com',
    iosClientId: '479462375089-ajstjngpofn4dvbbd59j5s8ihj1b4di1.apps.googleusercontent.com',
    iosBundleId: 'com.qm',
  );
}
